open-compass/VLMEvalKit

- README.md
- vlmeval/config.py
- vlmeval/smp/misc.py
- vlmeval/vlm/__init__.py
- vlmeval/vlm/llava.py
- vlmeval/vlm/qwen_vl.py
1. Support LLaVANext 
2. Update QwenVL according to the official evaluation paradigm
> [Model] Support LLaVANEXT

- Quickstart.md
- vlmeval/evaluate/misc.py
The default setting mentioned above uses OpenAI's GPT as the judge LLM. However, you can also deploy a local judge LLM with [LMDeploy](https://github.com/InternLM/lmdeploy).
First install:
```
pip install lmdeploy openai
```
And then deploy a local judge LLM with the single line of code. LMDeploy will automatically download the model from Huggingface. Assuming we use internlm2-chat-1_8b as the judge, port 23333, and the key sk-123456 (the key must start with "sk-" and follow with any number you like):
```
lmdeploy serve api_server internlm/internlm2-chat-1_8b --server-port 23333
```
You need to get the model name registered by LMDeploy with the following code:
```
from openai import OpenAI
client = OpenAI(
api_key='sk-123456',
base_url="http://0.0.0.0:23333/v1"
)
model_name = …
```
> Allow to use local judge llm

- Quickstart.md
- README.md
- vlmeval/evaluate/misc.py
- Get the env variable inside `build judge`, otherwise LOCAL_LLM has not been read from .env file before we set it.
-  Improve readme. Add task types of the dataset
-  Improve readme. In fact, if the open ai key is set, the repo will always extract answers with judge LLM. Only when the key is not set, it will try exact matching mode
> allow set local llm in the .env file; improve readme

- run.py
- vlmeval/api/gpt.py
- vlmeval/evaluate/llavabench.py
- vlmeval/evaluate/mathvista_eval.py
- vlmeval/evaluate/mmvet_eval.py
- vlmeval/evaluate/multiple_choice.py
- vlmeval/evaluate/yes_or_no.py
1. new env variables can be set in .env
```bash
OPENAI_API_KEY_JUDGE=
OPENAI_API_BASE_JUDGE=
```
2. Support set the judge model with `--judge` in run.py
3. `--retry` also applies to judge model in run.py
> [Improvement] Use judge_kwargs for initializing judges

- README.md
- vlmeval/config.py
- vlmeval/evaluate/mathvista_eval.py
- vlmeval/vlm/internvl_chat.py
Hi, developers of VLMEvalKit:
Thanks for developing such a good toolkit for multi-modal evaluation!
We recently developed a new InternVL-Chat model ([InternVL-Chat-V1-5](https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5-Preview)) that achieves many SOTA performance on multimodal benchmarks. We apply to add this model to OpenCompass Multi-modal Leaderboard.
There are two major changes in this PR:
1. add a new model, [InternVL-Chat-V1-5](https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5-Preview), the model weights have been open-sourced.
2. fix prompts for old models, including InternVL-Chat-V1-1, InternVL-Chat-V1-2, and InternVL-Chat-V1-2-Plus.
We test this model using transformers==4.36.2, but I think 4.37.0 should work as well.
> Add InternVL-Chat-V1-5

- vlmeval/vlm/xcomposer/xcomposer.py
Torch Version: 2.1.2+cu121
Traceback (most recent call last):
File "/mnt/petrelfs/wangjize/VLMEvalKit/run.py", line 152, in <module>
main()  File "/mnt/petrelfs/wangjize/VLMEvalKit/run.py", line 74, in main    model = infer_data_job(
File "/mnt/petrelfs/wangjize/VLMEvalKit/vlmeval/inference.py", line 164, in infer_data_job
model = infer_data(
File "/mnt/petrelfs/wangjize/VLMEvalKit/vlmeval/inference.py", line 130, in infer_data    response = model.generate(message=struct, dataset=dataset_name)  File "/mnt/petrelfs/wangjize/VLMEvalKit/vlmeval/vlm/base.py", line 135, in generate
return self.generate_inner(message, dataset)
File "/mnt/petrelfs/wangjize/VLMEvalKit/vlmeval/vlm/xcomposer/xcomposer.py", line 65, in generate_inner
prompt_embs = self.message_to_prompt_embs(message, dataset)
File …
> Fix xcomposer error during inference

- vlmeval/api/__init__.py
- vlmeval/api/glm_vision.py
- vlmeval/config.py
> Feature add glmv

- vlmeval/config.py
- vlmeval/vlm/internvl_chat.py
Hello, 
we have released a new model, [Mini-InternVL-Chat-2B-V1-5](https://huggingface.co/OpenGVLab/Mini-InternVL-Chat-2B-V1-5), which has only 2.2B parameters. It consists of InternViT-300M-448px, MLP projector, and InternLM2-Chat-1.8B. Although it has only 8.6% of the parameters of InternVL-Chat-V1-5, it can achieve 80-90% of its performance. I am now requesting to add this smaller model to VLMEvalKit.
Below are the results I obtained using VLMEvalKit:
```
torchrun --nproc-per-node=8 run.py --data MMBench_DEV_EN --model Mini-InternVL-Chat-2B-V1-5 --verbose
```
The result is:
```
2024-05-24 23:38:26,074 - Evaluation - INFO -   split   Overall  ...  spatial_relationship  structuralized_imagetext_understanding
0   dev  0.706186  ...              0.266667 …
```
> Add Mini-InternVL-Chat-2B-V1-5

- vlmeval/api/gpt.py
This PR is to support Azure OpenAI ([reference](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference)) for GPT4V families.
Note: API difference between OpenAI and Azure OpenAI is in [here](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/switching-endpoints).
Example usage is as follows.
```python
from vlmeval.config import supported_VLM
model = supported_VLM['GPT4o'](use_azure=True)
ret = model.generate(['assets/apple.jpg', 'assets/apple.jpg', 'How many apples are there in the provided images? '])
```
> Support Azure OpenAI API

- README.md
- docs/en/Development.md
- docs/ja/README_ja.md
- docs/zh-CN/Development_zh-CN.md
- docs/zh-CN/README_zh-CN.md
The dataset name displaying for VCR is a little problematic since it shows italic font for the underscore.
Before change:
After change:
Thank you!
> Change the displaying of the Dataset Name

- vlmeval/smp/vlm.py
Replace the operation of writing to disk when converting base64 images with in-memory operations to improve performance.
> convert base64 images -> disk to memory

- vlmeval/vlm/xgen_mm.py
Hi team,
This is Manli, one of the original authors of XGen-MM (BLIP3). Thank you all for contributing to support xGen-MM in your awesome eval toolkit. 
I was working on fixing some small issues with our Huggingface converted models. This PR is to update the `eos_token` for our tokenizer so the model knows to stop at `<|end|>`. 
(To clarify, in my local evaluation, I directly ran your toolkit using the model defined in the training code, which differs from the Huggingface converted one, so we don't have this `eos_token` issue with our local models.)
> Update eos_token for HF converted xgen-mm

- vlmeval/vlm/internvl_chat.py
以下是本次修改的说明：
1. 由于video数据集没有dump_image函数，在use_custom_prompt对遇到的所有Video数据集都返回False；
2. 修改了一下image数据集的prompt，把MME和HallusionBench都归类到了Y/N下面；
3. 在set_max_num中根据max_num做了数据集名称的list，方便之后拓展新的数据集；
4. cuda()的硬编码全部改成to(self.device)；
5. 图片的指代词改成了Image-{idx}，不同图像用`\n`区分；
6. 增加了MVBench的prompt；
经过测试，图像benchmark的点数没有变化，视频benchmark中Video-MME的点数没有变化，MMBench-Video的点数有轻微提升，MVBench的点数还需要进一步测试。
---
Here is an explanation of the changes made:
1. The dump_image function was not available for the video dataset, so use_custom_prompt returned False for all Video datasets encountered.
2. The prompt for image datasets was modified to categorize MME and HallusionBench under Y/N.
3. A list of dataset names based on max_num was created in set_max_num for future expansion of new datasets.
4. All hard-coded .cuda() calls …
> [Fix] Update prompts for InternVL2

- vlmeval/config.py
- vlmeval/tools.py
- vlmeval/vlm/__init__.py
- vlmeval/vlm/janus.py
We add [Janus-1.3B](https://github.com/deepseek-ai/Janus) model to reproduce the results in paper.
| | MME | MMB<br>(w/o circular) | SEED | MMMU_DEV_VAL | MM-Vet | POPE |
|---|---|---|---|---|---|---|
| VLMEvalkit (Reproduce) | 1342.4 | 69.8 | 63.8 | 31.2 | 36.8 | 85.5 (overall)<br>87.1 (random) |
| Paper | 1338.0 | 69.4 | 63.7 | 30.5 | 34.3 | 87 (random) |
You can run the evaluation with the following code:
``` bash
torchrun --nproc-per-node=8 run.py --data POPE MMMU_DEV_VAL MMBench_DEV_EN MME SEEDBench_IMG MMVet --model janus_1.3b --verbose
```
- We evaluate MMBench without circular mode. You should set `circular=False` in the file `vlmeval/dataset/image_mcq.py`
- We use the official evaluation of [MM-Vet](https://huggingface.co/spaces/whyu/MM-Vet_Evaluator) with GPT-4 evaluator.
> Add Janus-1.3B

- README.md
- vlmeval/config.py
- vlmeval/vlm/__init__.py
- vlmeval/vlm/h2ovl_mississippi.py
Adding evaluation code for H2OVL Mississippi models. It supports both single and multi-image scenarios, but not videos. 
The PR is lint checked. Following instructions from here: [advanced_guides](https://github.com/open-compass/VLMEvalKit/blob/main/docs/en/advanced_guides/Development.md)
> Add support for H2OVL Mississippi model series

- vlmeval/dataset/longvideobench.py
- vlmeval/dataset/mlvu.py
- vlmeval/dataset/mmbench_video.py
- vlmeval/dataset/mvbench.py
- vlmeval/dataset/tempcompass.py
- vlmeval/dataset/video_base.py
- vlmeval/dataset/videomme.py
- vlmeval/smp/misc.py
Set env `VLMEVALKIT_USE_MODELSCOPE=True` and `pip install modelscope`
you can download video benchmarks from modelscope automatically, which supports:
all dataset downloads have been tested.
> [Feat] add modelscope download video datasets

- README.md
- scripts/summarize.py
- vlmeval/dataset/image_mcq.py
VisOnlyQA is a dataset for evaluating the visual perception capabilities of LVLMs.
* Paper: https://arxiv.org/abs/2412.00947
* GitHub repository: https://github.com/psunlpgroup/VisOnlyQA
> [Benchmark] Add VisOnlyQA dataset

- README.md
- vlmeval/dataset/utils/naturalbench.py
- added info of NaturalBench in README.md
- fixed the metric names for NaturalBench Dataset
> [Added/FIxed] added info of NaturalBench in README.md and fixed the metric names for NaturalBench Dataset

- vlmeval/api/__init__.py
- vlmeval/api/taichu.py
- vlmeval/config.py
Add a new model to support opencompass evaluation.
> [MODEL] Add New Model API , Taichu-VL

- vlmeval/vlm/molmo.py
**Changes**:
- Process up to max 36 crops per image instead of 12 crops in default setting.
- Integrate prompts from the official Molmo implementation to match the reported numbers in the paper. (https://molmo.allenai.org/paper.pdf).
> [Model] Update Molmo Eval to Match Official Implementation

- vlmeval/api/siliconflow.py
- 修复图像resize 中 width，height 错误问题
> [Model] Update TeleMM - fix confusing image width&height

- vlmeval/vlm/llama_vision.py
First of all, we sincerely appreciate the work of VLMEvalKit and the tremendous contributions it has made to the entire VLM community! However, the current configuration of LLaVA-CoT (e.g., max_new_tokens) is incorrect, leading to significant deviations in the benchmark test results. This PR aims to correct the configuration of LLaVA-CoT.
> Correct the configuration of LLaVA-CoT

- vlmeval/dataset/__init__.py
- vlmeval/dataset/cgbench.py
- vlmeval/dataset/utils/cgbench.py
- vlmeval/dataset/video_dataset_config.py
Added support for the CG-Bench dataset by implementing the necessary dataset classes and configurations.
- Implemented CG-Bench dataset class in `vlmeval/dataset/cgbench.py`
- Added utility functions for CG-Bench in `vlmeval/dataset/utils/cgbench.py` 
- Registered the dataset in `vlmeval/dataset/__init__.py`
- Added configuration examples in `vlmeval/dataset/video_dataset_config.py`
> Add CGBench dataset support

- vlmeval/dataset/image_mcq.py
Add support for [3DSRBench](https://3dsrbench.github.io/). Data files are hosted on [huggingface.co](https://huggingface.co/datasets/ccvl/3DSRBench).
> Add 3DSRBench

- vlmeval/config.py
- vlmeval/vlm/__init__.py
- vlmeval/vlm/emu.py
Add emu3-chat and emu3-gen model inference support.
> add emu3-chat and emu3-gen

- run.py
This PR adds `--judge-args` option to pass judge arguments.
I wanted to use Azure OpenAI AI (ref. #214) when running a benchmark that requires the judge, but I couldn't find how to enable it in `run.py`.
With this PR, you can enable it by adding `--judge-args '{"use_azure": true}'`.
> Add judge args option

- vlmeval/config.py
- vlmeval/vlm/smolvlm.py
I added the paths for SmolVLM-256M and SmolVLM-500M. Additionally, I worked on the prompts for different benchmarks to match our internal evaluations. In particular, ChartQA went from 27% to 72% when we prompt the model to follow certain formatting rules.
> [Model] Add SmolVLM-256M and SmolVLM-500M and fix prompts for benchmarks

- vlmeval/vlm/pixtral.py
Hi,
Running evaluation of "Pixtral-12B" on any dataset throws an error saying:
```bash
File "/VLMEvalKit/vlmeval/vlm/pixtral.py", line 31, in __init__
self.tokenizer = MistralTokenizer.from_file(f'{cache_path}/tekken.json')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/python3.11/site-packages/mistral_common/tokens/tokenizers/mistral.py", line 190, in from_file
raise TokenizerException(f"Unrecognized tokenizer file: {tokenizer_filename}")
mistral_common.exceptions.TokenizerException: Unrecognized tokenizer file: None/tekken.json
ERROR - run.py: main - 411: Unrecognized tokenizer file: None/tekken.json, skipping this combination.
```
The reason is the missing argument `repo_type='models'` when calling `get_cache_path` function
> Fixed the cache_path in pixtral.py

- run.py
current implementation will not work if user use infer only mode under multiple processes
> [bug-fix] move barrier to the beginning of the for-loop

- vlmeval/smp/file.py
The original code failed to extract the dataset name correctly when the model name contains a period (e.g., "Qwen2.5-VL-3B"). This issue has been fixed by using the standard method to extract the file name without the extension.
The `suffix` variable isn't used and it's removed.
> [bug-fix] Fix bug in extracting dataset name from eval file name

- vlmeval/config.py
The qwen2.5vl evaluation did not use custom prompts but instead maintained consistency with the ones in the official repository.
> fix(qwen2.5vl) qwen2.5vl evaluation do not use custom prompt

- vlmeval/dataset/__init__.py
- vlmeval/dataset/utils/vlm2bench.py
- vlmeval/dataset/vlm2bench.py
This PR introduces **2860 image VQA pairs** from [VLM2Bench](https://github.com/vlm2-bench/VLM2-Bench) to enhance the evaluation set.
I am **Dongyu (Rain) Yao**, the **co-first author** of the [VLM2Bench paper](https://arxiv.org/abs/2502.12084).  
I have thoroughly **checked all cases**, ensuring that they can be **inferred** and **evaluated** using the **Qwen2.5-VL-7B-Instruct** model, producing results **comparable** to those reported in the paper.
- **Project Page**: [VLM2Bench](https://vlm2-bench.github.io/)
- **Paper**: [arXiv](https://arxiv.org/abs/2502.12084)
This addition aims to further benchmark **vision-language models** under diverse real-world scenarios.
> Integrate 2860 VQA Image Cases from VLM2Bench

- vlmeval/dataset/__init__.py
- vlmeval/dataset/image_mcq.py
- vlmeval/dataset/utils/vmcbench.py
Add VMCBench to image_mcq datasets. VMCBench is from "Automated Generation of Challenging Multiple-Choice Questions for Vision Language Model Evaluation" (CVPR 2025) [https://yuhui-zh15.github.io/AutoConverter-Website/](url). VMCBench is created by transforming 20 existing VQA datasets into a unified multiple-choice format, totaling 9,018 questions. Using VLMEvalKit, we comprehensively evaluate 28 state-of-the-art VLMs on VMCBench, setting a new standard for scalable, consistent, and reproducible VLM evaluation.
> Add VMCBench (CVPR 2025)

- vlmeval/dataset/vlm2bench.py
We corrected some cases in the .tsv file and uploaded the new version to our huggingface repo.
The link to our .tsv file has not changed, but we updated the new MD5 value for our .tsv file in the code.
We also rerun the following two models using this Evalkit (on RXT6000 GPUs):
**Qwen2.5-VL-7B-Instruct**
gc-mat: 41.6988416988417
gc-trk: 44.29223744292237
oc-cnt: 58.333333333333336
oc-cpr: 62
oc-grp: 54.5
pc-cnt: 67.5
pc-cpr: 79.5
pc-grp: 77
**InternVL2_5-8B**
gc-mat:  28.9575
gc-trk:  37.8995
oc-cnt:  58.8889
oc-cpr:  53.0556
oc-grp:  53
pc-cnt:  48.3333
pc-cpr:  44
pc-grp:  56
These results may differ slightly from those reported in the paper. This could be because the results in our paper were obtained using our inference script, and differences in parameter settings and the computing …
> VLM2Bench UPDATE: .tsv file for image cases and new md5 value

- vlmeval/dataset/moat.py
Sorry to bother again.
I check the code for MOAT and find some minor differences from our original settings.
1. shuffle the choices if given
2. for outside knowledge text, LMMs should be told this is a hint
Theoretically, these should not cause significant performance changes. But setting so will make the implementation more consistent. We conduct a test ourselves with GPT4o_HIGH and the result is similar to ours in the paper.
(It is reasonable for results changing minorly every time, since the shuffle and the uncertainty of model itself)
Sorry again and thank you for your help.
> [benchmark][MOAT] Shuffle choices for MOAT

- docs/en/ConfigSystem.md
- docs/zh-CN/ConfigSystem.md
Remove the trailing comma of the example of the JSON file.
> [Doc] Remove trailing comma

- vlmeval/vlm/ovis/ovis.py
Since `vlmeval check` doesn't pass the dataset param to the ovis2's prepare_inputs function, then dataset=None. Thus, when in [line 494](https://github.com/open-compass/VLMEvalKit/blob/66a76843f260a57e2236150bcf0b7df9c2d82f88/vlmeval/vlm/ovis/ovis.py#L494), it will raise error:
```
user@host $ vlmutil check Ovis2-8B
......
File "/data/XXX/Item/VLMEvalKit/vlmeval/vlm/ovis/ovis.py", line 494, in <genexpr>
dataset.startswith(prefix) for prefix in
^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'
```
After fix:
```
user@host $ vlmutil check Ovis2-8B
......
Test 1: The image shows a single, ripe red apple with a glossy surface and a small green leaf attached to its stem. The apple is positioned against a plain white background, which highlights its vibrant red …
```
> [Fix] Fix errors when `vlmeval check` ovis2 models

- vlmeval/api/lmdeploy.py
- Some VLMs like Phi-4-multimodal use [vision LoRA adapter](https://huggingface.co/microsoft/Phi-4-multimodal-instruct/tree/main/vision-lora) for vision tasks. However, current `LMDeployWrapper` can only always set `model` as base model automatically, causing incorrect evaluation results.
- This PR exposes `model` for `LMDeployWrapper` so that users can configure model name and send LoRA requests during evaluation to get correct responses.
> [API] Allow setting model name for `LMDeployWrapper`

- vlmeval/dataset/creation.py
Using GPT-4o-20241120 as the judge model sometimes generates answers like "**FINAL VERDICT IS:...", which cannot be extracted correctly by the old function.
> [Benchmark] Fix function extract_subjective in CreationBench

- vlmeval/inference.py
- vlmeval/inference_mt.py
In the code, the infer_data function in both vlmeval\inference.py and vlmeval\inference_mt.py returns null when a dataset has already been evaluated. This behavior is problematic because the function is called as model = infer_data(...), meaning we need to pass the model forward. If it returns null, the already loaded model will be lost, leading to unexpected results when processing subsequent datasets (i.e., those that haven't been fully evaluated yet).
> Fix all_finished return null

- vlmeval/dataset/mmifeval.py
Fix bug in MM-IFEval like "TypeError: tuple indices must be integers or slices, not str" when loading tmp_file.
> Fix tmp ans load error in MM-IFEval

- vlmeval/dataset/__init__.py
- vlmeval/dataset/charxiv.py
CharXiv benchmark is a visual question answer (VQA) that is specified on Chart domain. CharXiv consists of two splits (val, test) and two modes descriptive and reasoning, this PR completes val split, reasulting two testable benchmarks:
- `CharXiv_reasoning_val`, consisting 1000 images, each corresponding 1 question
- `CharXiv_descriptive_val`, consisting 1000 images (shared with reasoning mode), each corresponding to 4 questions.
Modification: the original benchmark groups answer to simplify grading process, in this PR, each line is processed individually
Evaluated results (Qwen-VL-Plus) with qwen-plus as judge model):
Reasoning Validation Results:
|   Text-in-Chart |   Number-in-Chart |   Number-in-General |   Text-in-General |   Overall | …
> [Benchmark]: Support CharXiv Benchmark (#921)

- requirements.txt
- vlmeval/api/gemini.py
- vlmeval/config.py
This PR adds support for the thinking_budget parameter in Gemini-2.5Pro, enabling configurable thinking capabilities in the model API.
> [Model] Add support for Gemini-2.5Pro thinking

- vlmeval/smp/log.py
Logging messages were duplicated because module-level loggers propagated messages to the root logger, causing each log entry to appear twice in the output.
This PR sets  **`logger.propagate = False`** in module-level loggers. This ensures that logs handled by module-level loggers are not propagated to the root logger, thereby eliminating duplicate log entries.
Logs now correctly appear once per event, clearly indicating their source without duplication.
> [Fix] Fix duplicate logging by disabling propagation

- .gitignore
- requirements.txt
- vlmeval/api/cloudwalk.py
- vlmeval/dataset/cgbench.py
- vlmeval/dataset/longvideobench.py
- vlmeval/dataset/mlvu.py
- vlmeval/dataset/mvbench.py
- vlmeval/dataset/qbench_video.py
- vlmeval/dataset/tamperbench.py
- vlmeval/dataset/tempcompass.py
- vlmeval/dataset/utils/cgbench.py
- vlmeval/dataset/video_base.py
- vlmeval/dataset/videomme.py
- vlmeval/dataset/worldsense.py
- vlmeval/smp/misc.py
- vlmeval/vlm/long_vita.py
- vlmeval/vlm/valley/requirements_valley.txt
- vlmeval/vlm/video_llm/chat_uni_vi.py
- vlmeval/vlm/video_llm/llama_vid.py
Remove Decord Dependancy:
1. decord is only used by video LMMs and benchmarks
2. it's difficult to install decord on linux arm machines
> [Fix] Remove Decord Dependancy

- vlmeval/dataset/utils/chartmimic/evaluator/chart_type_evaluator.py
- vlmeval/dataset/utils/chartmimic/evaluator/color_evaluator.py
- vlmeval/dataset/utils/chartmimic/evaluator/grid_evaluator.py
- vlmeval/dataset/utils/chartmimic/evaluator/layout_evaluator.py
- vlmeval/dataset/utils/chartmimic/evaluator/legend_evaluator.py
- vlmeval/dataset/utils/chartmimic/evaluator/text_evaluator.py
the existing import breaks module loading due to incorrect relative path usage
> fix relative import for run_script_safe from eval_configs

- vlmeval/dataset/videomme.py
Fix VideoMME evaluate when `data['index'] != range(len(data))`
> [Fix] Fix VideoMME evaluate

- vlmeval/config.py
- vlmeval/vlm/__init__.py
- vlmeval/vlm/varco_vision.py
Hi. I want to add a new model.
This is our HF url: https://huggingface.co/NCSOFT/VARCO-VISION-2.0-14B
Thanks :)
> [Model] Add varco-vision-2.0-14b

- run.py
- vlmeval/dataset/__init__.py
- vlmeval/dataset/image_base.py
- vlmeval/dataset/image_mcq.py
- vlmeval/dataset/image_vqa.py
- vlmeval/dataset/utils/llavabench.py
[MMBench_DEV_KO](https://huggingface.co/datasets/NCSOFT/K-MMBench), [SEEDBench_IMG_KO](https://huggingface.co/datasets/NCSOFT/K-SEED), [MMStar_KO](https://huggingface.co/datasets/NCSOFT/K-MMStar), [LLaVABench_KO](https://huggingface.co/datasets/NCSOFT/K-LLaVA-W) are new benchmarks created in Korean based on MMBench, SEEDBench_IMG, MMStar and LLaVABench respectively.
Also, [K-DTCBench](https://huggingface.co/datasets/NCSOFT/K-DTCBench) is a newly developed benchmark featuring both computer-generated and handwritten images of three different types (documents, tables, and charts), all written in Korean.
The paper is here: https://arxiv.org/pdf/2411.19103
Thank you :)
> [Benchmark] Add MMBench_DEV_KO, SEEDBench_IMG_KO, MMStar_KO, K-DTCBench, LLaVABench_KO

- vlmeval/utils/matching_util.py
Some of the answers are too complex, causing "can_infer" to be mismatched.
dev model:
[xhs_api-temperature0.7-32k_MMMU_DEV_VAL_openai_result.xlsx](https://github.com/user-attachments/files/21384566/xhs_api-temperature0.7-32k_MMMU_DEV_VAL_openai_result.xlsx)
seedvl1.5:
[xhs-seedvl-1.5_old_MMMU_DEV_VAL_openai_result.xlsx](https://github.com/user-attachments/files/21384658/xhs-seedvl-1.5_old_MMMU_DEV_VAL_openai_result.xlsx)
dev model:
[fixed_xhs_api-temperature0.7-32k_MMMU_DEV_VAL_openai_result.xlsx](https://github.com/user-attachments/files/21384584/fixed_xhs_api-temperature0.7-32k_MMMU_DEV_VAL_openai_result.xlsx)
seedvl1.5:
[fixed_xhs-seedvl-1.5_MMMU_DEV_VAL_openai_result.xlsx](https://github.com/user-attachments/files/21384656/fixed_xhs-seedvl-1.5_MMMU_DEV_VAL_openai_result.xlsx)
seedvl …
> Improve `can_infer_option` and `can_infer_text`

- vlmeval/dataset/utils/vqa_eval.py
There was a bug in the call to the relaxed_correctness function, where the order of the target and prediction parameters was reversed.
> fix: correct relaxed_correctness parameter order
