open-compass/VLMEvalKit

vlmeval/config.py, vlmeval/vlm/__init__.py, vlmeval/vlm/transcore_m.py
=> TranCore-M 20231208

vlmeval/utils/data_util.py
add md5 check function in vlmeval/utils/data_util.py, in order to prevent the locally stored data file is incomplete.
=> add dataset md5 check integrity

README.md, vlmeval/config.py, vlmeval/vlm/__init__.py, vlmeval/vlm/mmalaya.py
We have developed MMAlaya based on the large language model Alaya-7B-Chat and blip2-opt-2.7b using the LLaVA architecture. Although its current scores are not high, we hope to receive validation in the excellent VLMEvalKit.
=> Add MMAlaya 

run.py, vlmeval/evaluate/vqa_eval.py, vlmeval/evaluate/yes_or_no.py, vlmeval/inference.py, vlmeval/smp/misc.py, vlmeval/utils/custom_prompt.py, vlmeval/utils/dataset.py
1. Create image directory only when necessary. 
2. Support setting the work directory. 
3. Refine yes or no evaluation (match yes / no with words in outputs instead of the entire sentence).
=> [Feature] Minor Updates

run.py, vlmeval/api/base.py, vlmeval/utils/dataset_config.py
1. Reduce the latency of API calling
2. Refine DATASET_TYPE related logics
=> [Improvement] Minor Updates 0202

vlmeval/api/__init__.py, vlmeval/api/claude.py, vlmeval/config.py
=> add claude3-vision

vlmeval/vlm/llava/llava.py
LLaVA and LLaVA-NeXT now supports interleave inputs.
=> [Improvement] LLaVA Interleave

vlmeval/vlm/llava/llava.py
1. Fix the failure of LLaVA when evaluating on MMMU. 
2. After this update, LLaVA supports interleave inputs, while LLaVA-Next (based on the transformer official implementation) still cannot.
=> [Fix] LLaVA Interleave

vlmeval/vlm/idefics.py
=> [Improvement] Idefics2 almost matching prompts

README.md, README_zh-CN.md, run.py, vlmeval/evaluate/multiple_choice.py, vlmeval/smp/file.py, vlmeval/utils/dataset_config.py
=> [Dataset] MMBench V11

vlmeval/vlm/cogvlm.py
- 修复 cogvlm 与 glm4v-9b 在选择和判断题上的 prompts 问题
=> update prompts for cogvlm & GLM4v-9B

vlmeval/config.py, vlmeval/vlm/internvl_chat.py
There are still some tests that have not been completed.
=> Support InternVL2 series

vlmeval/dataset/mmbench_video.py
Same as #244 , to save efforts after refactoring
=> [Fix] Update MMBench-Video Prompt for no-pack setting

vlmeval/config.py, vlmeval/vlm/bunnyllama3.py
Bunny team customizes some prompts to make the results of VLMEvalKit more consistent with Bunny official results.
And Bunny-v1.1-Llama-3-8B-V has been released.
=> Customize prompt for Bunny

README.md, docs/ja/README_ja.md, docs/zh-CN/README_zh-CN.md, vlmeval/dataset/__init__.py, vlmeval/dataset/image_vqa.py
The benchmark is contributed by Jinghui Lu.
=> [Dataset] Support MT-VQA

README.md, run.py, vlmeval/config.py, vlmeval/dataset/__init__.py, vlmeval/dataset/mmbench_video.py, vlmeval/dataset/utils/videomme.py, vlmeval/dataset/video_base.py, vlmeval/dataset/videomme.py, vlmeval/inference_video.py
This pull request adds support for the [Video-MME](https://video-mme.github.io/) dataset to enhance video understanding capabilities within the project. We have passed all the pre-commit tests.
=> Add Support for Video-MME

README.md, docs/zh-CN/README_zh-CN.md, vlmeval/config.py, vlmeval/vlm/__init__.py, vlmeval/vlm/ovis.py
Thank you for the excellent project. We would like to propose adding support for [Ovis1.5](https://github.com/AIDC-AI/Ovis), which is fully open-source (including training data, training code, and model weights) and demonstrates impressive performance as evaluated using VLMEvalKit.
=> [Model] Add support for Ovis1.5

README.md, vlmeval/config.py, vlmeval/vlm/__init__.py, vlmeval/vlm/vila.py
VILA Added !
Will share evals later this week. To test -
1. First install VILA
2. Then Install VLMEvalKit
```
cd VILA
conda create -n vila python=3.10 -y # make sure you install python 3.10
conda activate vila
pip install -e .
cd ../VLMEvalKit
pip install -e .
pip install transformers==4.36.2
```
```
python  run.py --data MMMU_DEV_VAL  --model vila_8b --verbose 
.
.
.
The net cash flow per check from adopting the lockbox system is $8.65. The total collection time will be reduced by three days, and the average number of payments per day is 410. The average value of payment is $86.5, and the variable lockbox fee is $50 per transaction. Therefore, the net cash flow per check from adopting the lockbox system is $8.65.
0%|▏                                                               | 4/1050 …
```
=> VILA added

vlmeval/vlm/internvl_chat.py
Hi, dear VLMEvalKit developers:
In this PR, I have modified the prompt of the InternVL model test video dataset in the best way.
=> Align video performance of InternVL

.pre-commit-config.yaml, vlmeval/config.py, vlmeval/dataset/image_mcq.py, vlmeval/vlm/__init__.py, vlmeval/vlm/mantis.py
As the title suggests, this pr is to add the [Mantis](https://arxiv.org/abs/2405.01483) model to the supported model list.
Supported Models:
The implementation supports 6 Mantis model from the [Mantis huggingface collection](https://huggingface.co/collections/TIGER-Lab/mantis-6619b0834594c878cdb1d6e4)
=> Add the Mantis Model to the support model list

vlmeval/dataset/__init__.py, vlmeval/dataset/text_base.py, vlmeval/dataset/text_mcq.py, vlmeval/vlm/llava/llava.py
Add code for TextMCQDataset and CustomTextMCQDataset
There is only code, and no real data set is provided
=> Add code of Text dataset

.pre-commit-config.yaml, vlmeval/config.py, vlmeval/dataset/image_mcq.py, vlmeval/vlm/__init__.py, vlmeval/vlm/mantis.py
warnings.info('Note that AesBench VAL is just a toy version of AesBench TEST. For full results, \                                                                                                                                                                                   
[rank0]: AttributeError: module 'warnings' has no attribute 'info'
=> To fix up a error when evaluate on A-Bench_VAL

.gitignore, vlmeval/tools.py
1. The Phi-3-Vision model is added in the transformers version (4.40.0)
2. The run command supports multiple model lists
3. A warning is added for models not existing in the map
4. .idea/ is added to .gitignore
=> [Update] update models map in tools && update command run 

README.md, docs/en/Development.md, docs/zh-CN/README_zh-CN.md, vlmeval/dataset/image_mcq.py
Thanks authors for releasing this fantastic repo! I have added the code for supporting MMMB and Multilingual MMBench. Below are the links to the [official GitHub repository](https://arxiv.org/abs/2406.02539) and [HuggingFace dataset](https://huggingface.co/datasets/AIDC-AI/Parrot-dataset) for our work.
=> [Benchmark] Add MMMB and Multilingual MMBench

vlmeval/inference_video.py
=> Fix bug in inference_video.py

vlmeval/vlm/idefics.py, vlmeval/vlm/mmalaya.py
When `max_num` = 24, the model requires two 80GB GPU for evaluation.
Otherwise, it only requires one 80GB GPU.
For multi-image scenarios, the max_num for each image is `max(1, max_num / num_image)`
=> [Minor] Fix MMAlaya2

vlmeval/tools.py
1. fix "output" path problem in tools.py
2. Add more logs making it possible to see which dataset is currently being run,
3. Make it possible for multiple dataset runs to continue to the next dataset when one fails
=> [Minor] Fix path problem in tools.py && Add log

vlmeval/dataset/__init__.py, vlmeval/dataset/image_mcq.py, vlmeval/dataset/utils/hrbench.py, vlmeval/vlm/internvl_chat.py
The HR-Bench benchmark was introduced to assess the perception capabilities of MLLMs when working with high-resolution images, specifically those in 4K and 8K resolution. The paper is here: [link](https://arxiv.org/abs/2408.15556).
=> [Benchmark] Supported HR-Bench

vlmeval/dataset/image_mcq.py, vlmeval/vlm/internvl_chat.py, vlmeval/vlm/minicpm_v.py, vlmeval/vlm/mmalaya.py, vlmeval/vlm/rbdash.py, vlmeval/vlm/xcomposer/xcomposer2d5.py
Resolved the issue where some model prompts did not match the MME-RealWorld dataset.
=> mme-realworld-prompt

vlmeval/config.py, vlmeval/vlm/__init__.py, vlmeval/vlm/minimonkey.py
This pr intends to enhance the functionality of VLMEvalKit by supporting MiniMonkey model in Monkey series, which is not covered in latest version. Three files are involved, including vlmeval/config.py, vlmeval/vlm/__init__.py and vlmeval/vlm/minimonkey.py.
=> support MiniMonkey model

.pre-commit-config.yaml, vlmeval/dataset/__init__.py
This pull request introduces support for pre-commit.ci in the repository to automate code quality checks and apply automatic fixes during the pull request process. The following enhancements have been made:
- **Added pre-commit.ci configuration** in the `.pre-commit-config.yaml` file to enable automatic code fixing and regular hook updates.
- Configured **weekly autoupdate** schedule to ensure that hooks remain up-to-date.
- **Auto-fixing enabled** for pull requests, reducing manual intervention for minor code issues.
This integration will help streamline the development process by ensuring consistent code quality, allowing developers to focus on more valuable tasks.
Changes:
- 9 additions in `.pre-commit-config.yaml`.
Refer to [pre-commit.ci documentation](https://pre-commit.ci/) for …
=> [Feature]: Add pre-commit.ci integration for automated PR fixes

run.py, vlmeval/inference.py
Fix program error exit without synchronization.
=> Fix program error exit without synchronization.

README.md, vlmeval/config.py, vlmeval/tools.py, vlmeval/vlm/__init__.py, vlmeval/vlm/moondream.py
- [Moondream series](https://huggingface.co/vikhyatk)
- tested with `Moondream1` on `MME` datasets:
- tested with `Moondream2` on `MME` datasets:
=> [Models] add moondream1 and moondream2 models

README.md, run.py, vlmeval/dataset/__init__.py, vlmeval/dataset/image_vqa.py, vlmeval/dataset/utils/mathverse.py, vlmeval/tools.py, vlmeval/vlm/internvl_chat.py, vlmeval/vlm/mmalaya.py
Add [MathVerse](https://mathverse-cuhk.github.io/) for evaluation.
=> [Benchmark] MathVerse

vlmeval/vlm/internvl_chat.py
Fix `[rank0]: UnboundLocalError: local variable 'prompt' referenced before assignment` when running pope
=> Fix Y/N type error of POPE

README.md, vlmeval/config.py, vlmeval/vlm/__init__.py, vlmeval/vlm/kosmos.py
- tested on `MME` dataset
`observation`: It seems that Kosmos2 does not pre-train well with strong knowledge, resulting in poor performance on datasets that require extensive knowledge (testes with MMBench, overall only get 0.013), but it performance is as expected while testing on other dataset which do not require as much knowledge:
- `BLINK` dataset
- `LLavaBench`
- `MMMU`
- `MMStar`
- `MMVet`
=> [Model] add kosmos2

.github/workflows/lint.yml, .pre-commit-config.yaml, vlmeval/dataset/image_mcq.py, vlmeval/tools.py
Chunyi Li, providing R-Bench only for the (MCQ) task.
For the whole project with MCQ/VQA/CAP task please check https://github.com/Q-Future/R-Bench.
=> Adding R-Bench MCQ Section

.github/workflows/lint.yml, .pre-commit-config.yaml, README.md, vlmeval/config.py, vlmeval/dataset/image_mcq.py, vlmeval/tools.py, vlmeval/vlm/__init__.py, vlmeval/vlm/llava/llava.py, vlmeval/vlm/molmo.py, vlmeval/vlm/points.py
Added stopping criteria to the generation processes in LLaVA_Next2 and LLaVA_OneVision referencing https://github.com/LLaVA-VL/LLaVA-NeXT/blob/main/predict.py. This effectively prevents repetitive generation.
=> Add stopping criteria to LLaVA_Next2 and LLaVA_OneVision

vlmeval/vlm/pixtral.py
Fix the error related to the model path in Pixtral.
=> Fix the error related to the model path in Pixtral.

vlmeval/api/__init__.py, vlmeval/api/jt_vl_chat.py, vlmeval/config.py, vlmeval/dataset/utils/mathvista.py
=> Support JT-VL-Chat

vlmeval/config.py, vlmeval/vlm/pixtral.py
=> Fix some typos

vlmeval/config.py, vlmeval/vlm/__init__.py, vlmeval/vlm/vintern_chat.py
Architecture: InternVL
Parameters: 3B
LLM: Qwen2.5-3B-Instruct
Vision tower: InternViT-300M-448px
Homepage: https://huggingface.co/5CD-AI/Vintern-3B-beta
=> [Model] Support Vintern

vlmeval/config.py, vlmeval/dataset/mvbench.py, vlmeval/vlm/llava/llava.py
add the code support for llava_video: https://huggingface.co/collections/lmms-lab/llava-video-661e86f5e8dabc3ff793c944
=> [Model] add support for llava_video

run.py
Add `barrier()` for each eval and `destroy_process_group` at the end
=> [Improvement] Refine run.py

run.py
=> [Fix] Fix run.py

vlmeval/dataset/image_mcq.py
=> [Benchmark] Support WorldMedQA-V

vlmeval/dataset/mvbench.py
Resolved the following issues:
Improved handling of missing video files.
Corrected file construction errors within the 'move files' process.
Updated the preprocessing step to first unzip files, then proceed with moving them.
=> fixed MVBench preprocessing

vlmeval/dataset/__init__.py
Fixed minor issue in function DATASET_MODALITY that would cause model loading to fail when dataset was not specified.
=> [Fix Minor] Fix DATASET_MODALITY

vlmeval/config.py, vlmeval/vlm/__init__.py, vlmeval/vlm/smolvlm.py
soon to be released model by Hugging Face. We would like to mention that it is integrated in VLMEvalKit when we launch it. Thank you!
=>  [Model] Support SmolVLM

README.md
[Benchmark] Added MMGenBench benchmark
=> [Benchmark] Added MMGenBench benchmark

vlmeval/api/bailingmm.py
update bailingmm request keyword in json
=> Feature update bailingmm

requirements.txt
refer to : https://github.com/dmlc/decord/issues/213
=> [Feat] Support Mac device with arm CPU

.gitignore, vlmeval/api/siliconflow.py, vlmeval/config.py
TeleMM多模态大模型是由中国电信自主研发的多模态理解大模型，能够处理文本、图像等多种模态输入，支持图像理解、图表分析等功能，为用户提供跨模态的理解服务。模型能够与用户进行多模态交互，准确理解输入内容，回答问题、协助创作，并高效提供多模态信息和灵感支持。在细粒度感知，逻辑推理等多模态任务上有出色表现。
链接：https://cloud.siliconflow.cn/playground/chat/17885302607 (注：API key从该链接中获取，并在.env中配置SiliconFlow_API_KEY)
1. 模型性能提升
2. 推理速度优化，相比上一版提速 0.5 倍以上
python run.py --data MMMU_DEV_VAL --model TeleMM --nproc 12
由于API限制，nproc上限为12。
=> [Model] Update TeleMM

vlmeval/dataset/__init__.py, vlmeval/dataset/cmmmu.py
=> [benchmark] add new benchmark: CMMMU

vlmeval/config.py, vlmeval/vlm/internvl/internvl_chat.py, vlmeval/vlm/internvl/utils.py
update [InternVL2.5-MPO series](https://internvl.github.io/blog/2024-12-20-InternVL-2.5-MPO/)
=> update InternVL2.5-MPO series

run.py, vlmeval/config.py, vlmeval/vlm/__init__.py, vlmeval/vlm/deepseek_vl2.py
Hi VLMEvalKit Team,
This PR is for adding [DeepSeek-VL2](https://github.com/deepseek-ai/DeepSeek-VL2/) model. We used incremental prefilling to allow the deepseek-vl2-small run in 40GB GPUs.
The reproduction results are as follows:
| Model            | MMMU-Val | RealWorldQA | MMStar | AI2D-test | ChartQA | OCRBench | TextVQA-val |
|------------------|----------|-------------|--------|-----------|---------|----------|-------------|
| DSVL-2-small     |          |             |        |           |         |          |             |
| VLMEvalKit       | 47.8     | 69.4        | 57.0   | 79.0      | 84.48   | 835      | 83.34       |
| Paper            | 48.0     | 65.4        | 57.0   | 80.0      | 84.5    | 834      | 83.4        |
| DSVL-2-tiny      |          |             |        | …
=> [Model] Add DeepSeek-VL2

vlmeval/config.py, vlmeval/vlm/__init__.py, vlmeval/vlm/minicpm_v.py
=> Add MiniCPM-o-2_6

vlmeval/dataset/image_vqa.py
add dynamic evaluation by yangyue
=> Add MMVet_Hard

vlmeval/vlm/minicpm_v.py
Fix num_beams for MiniCPM-o-2_6
=> Fix num_beams for MiniCPM-o-2_6

vlmeval/vlm/moondream.py
Updated the Moondream2 VLM to reflect new 2025-01-09 release.
Changes:
- Use new 2025-01-09 release ([blog here](https://moondream.ai/blog/introducing-a-new-moondream-1-9b-and-gpu-support))
- Custom prompts for certain datasets
- use new .query() api instead of deprecated .generate()
- use new prompt template for passing image + text to .query()
=> Moondream2 2025-01-09 Release Update

run.py, vlmeval/dataset/__init__.py, vlmeval/dataset/image_mcq.py, vlmeval/smp/file.py, vlmeval/tools.py
In this PR we support the standard (10 opts) and vision evaluation modes for MMMU Pro. 
The Evaluation Results of GPT4o-MINI is a little bit inferior to the numbers reported by the papar:
| Entry | Standard (10 opts) | Vision | 
| -- | -- | -- |
| GPT4o-MINI (reported) | 39.9 | 35.2 |
| GPT4o-MINI (COT, VLMEvalKit) | 38.2 | 33.5 |
=> [Benchmark] Support MMMU Pro

vlmeval/config.py, vlmeval/vlm/__init__.py, vlmeval/vlm/ovis/__init__.py, vlmeval/vlm/ovis/ovis.py, vlmeval/vlm/ovis/utils/mdp3.py
Reference evaluation environment: torch==2.4.0, torchvision==0.19.0, transformers==4.46.2, numpy==1.25.0, pillow==10.3.0, flash-attn==2.7.0.post2
=> [Model] Add Ovis2

run.py, vlmeval/dataset/__init__.py, vlmeval/dataset/mmalignbench.py, vlmeval/vlm/internvl/internvl_chat.py, vlmeval/vlm/minicpm_v.py
Add MM-AlignBench in OmniAlign-V: Towards Enhanced Alignment of MLLMs with Human Preference
=> Mmalignbench

vlmeval/config.py, vlmeval/vlm/__init__.py, vlmeval/vlm/long_vita.py
Hi, VLMEvalKit team,
We are excited to submit Long-VITA, a series of SOTA open-source vision-language models capable of processing up to 1 million tokens (including images, videos, and text).
GitHub Repository: https://github.com/VITA-MLLM/Long-VITA
Paper: [Long-VITA: Scaling Large Multi-modal Models to 1 Million Tokens with Leading Short-Context Accuracy](https://arxiv.org/abs/2502.05177v1)
Best regards
=> [Model] Add new model: Long-VITA

vlmeval/vlm/qwen2_vl/model.py
Modify the judge condition of Qwen2.5VL series.
=> Optimize init of qwen25vl

vlmeval/config.py, vlmeval/vlm/__init__.py, vlmeval/vlm/smolvlm.py
Adding the recently released SmolVLM2
@kennymckormick could you help us get SmolVLM2 merged? mentioning you because you helped us with the first SmolVLM merge.
Thank you!!
=> [Model] adding SmolVLM2

vlmeval/config.py, vlmeval/vlm/__init__.py, vlmeval/vlm/vlm_r1.py
This pull request introduces support for the VLM-R1 model.
If you have any questions, please let me know in time!
=> [Model] Add Support for VLM-R1 Model

.github/scripts/assert_score.py, .github/workflows/pr-run-test.yml
=> test(CI): add tests on pr stage

vlmeval/dataset/__init__.py, vlmeval/dataset/image_vqa.py
We add the [MME-CoT](https://github.com/CaraJ7/MME-CoT) evaluation code. MME-CoT is a visual reasoning benchmark for detailed CoT evaluation.
=> Add MME-CoT 

README.md, docs/ja/README_ja.md, docs/zh-CN/README_zh-CN.md, vlmeval/config.py, vlmeval/vlm/__init__.py, vlmeval/vlm/aki.py
Add the script and the Transformers version description of [Sony/AKI-4B-phi-3.5-mini](https://huggingface.co/Sony/AKI-4B-phi-3.5-mini).
=> [Model] Add AKI model

vlmeval/api/__init__.py, vlmeval/api/taichu.py, vlmeval/config.py
Add a new model  with API : Taichu - VLR
Temporary delete Taichu-2B.
=> [Model] Add Taichu-VLR model

vlmeval/config.py, vlmeval/vlm/__init__.py, vlmeval/vlm/ristretto.py
Reference evaluation environment: transformers==4.37.0, flash-attn==2.3.6
=> [Model] Add Ristretto

vlmeval/dataset/__init__.py, vlmeval/dataset/image_mcq.py, vlmeval/dataset/utils/multiple_choice.py, vlmeval/utils/__init__.py, vlmeval/utils/matching_util.py, vlmeval/vlm/qwen2_vl/prompt.py
Add support for [LEGO-Puzzles](https://tangkexian.github.io/LEGO-Puzzles/).
=> [Benchmark] Add LEGO-Puzzles Benchmark

vlmeval/dataset/image_mcq.py
add MMVP benchmark
huggingface repo: https://huggingface.co/datasets/MaoSong2022/MMVP
original MMVP github: https://github.com/tsb0601/MMVP
original MMVP huggingface: https://huggingface.co/datasets/MMVP/MMVP
=> [Benchmark] Support MMVP Benchmark

run.py, vlmeval/api/base.py, vlmeval/api/gpt.py, vlmeval/dataset/__init__.py, vlmeval/dataset/image_vqa.py, vlmeval/dataset/utils/physic.py, vlmeval/dataset/utils/physics_eval_utils.py
This PR adds the PHYSICS benchmark to the evaluation framework.
PHYSICS is an open-ended question answering benchmark covering university-level physics topics like classical mechanics, quantum mechanics, and thermodynamics.
Format: free-form QA
Source: PhD qualifying exams
Evaluation: symbolic checks (via SymPy) and natural language scoring (e.g., GPT-based)
Dataset repo: https://github.com/yale-nlp/Physics
This addition helps evaluate advanced physics reasoning capabilities of language models.
=> Add PHYSICS Benchmark for Open-Ended Physics Reasoning

vlmeval/config.py
你好，我们是抖音内容理解团队，在上次1.5版本的两个模型的基础上，我们新增一个SAIL-VL-1.6-8B模型，希望合入vlm仓库
=> 支持SAIL-VL-1.6

vlmeval/config.py
add support for Janus-Pro-1B [https://huggingface.co/deepseek-ai/Janus-Pro-1B](url)
=> [Model] add support for Janus-Pro-1B

run.py, vlmeval/dataset/__init__.py, vlmeval/dataset/image_mcq.py, vlmeval/dataset/utils/visulogic.py
[**🌐 Homepage**](https://visulogic-benchmark.github.io/VisuLogic) | [**🏆 Leaderboard**](https://visulogic-benchmark.github.io/VisuLogic/) | [**📖 Paper**](http://arxiv.org/abs/2504.15279) | [**🤗 Benchmark**](https://huggingface.co/datasets/VisuLogic/VisuLogic) | [**💻 Eval Code**](https://huggingface.co/datasets/VisuLogic/VisuLogic) | [**🤗 Train Data**](https://huggingface.co/datasets/VisuLogic/VisuLogic) | [**💻 Train Code**](https://github.com/VisuLogic-Benchmark/VisuLogic-Train)
VisuLogic is a newly designed benchmark aimed at evaluating the visual reasoning capabilities of Multi-modal Large Language Models (MLLMs), independent of textual reasoning processes. It features carefully constructed visual reasoning tasks spanning multiple categories, divided into six types based on required …
=> [Benchmark] Support VisuLogic

vlmeval/dataset/__init__.py, vlmeval/dataset/image_mcq.py
Add CVBench, including two sub tasks:
1. CV-Bench-2D
2. CV-Bench-3D
Evaluation:
- CV-Bench-2D, averaging on ADE20K and COCO
- CV-Bench-3D, accuracy
References:
- [Cambrain Project Page](https://cambrian-mllm.github.io/)
- [CVBench huggingface](https://huggingface.co/datasets/nyu-visionx/CV-Bench)
- [Cambrain-1 Paper Appendix C](https://arxiv.org/pdf/2406.16860)
=> [Benchmark] Support CVBench (CV-Bench-2D, CV-Bench-3D)

run.py
Currently, using the config and using vLLM cannot be done together. This PR fixes this issue, allowing these two features to be used simultaneously.
=> Fix vllm with config

vlmeval/dataset/__init__.py, vlmeval/dataset/image_mcq.py
I have supported the MicroVQA dataset here. It has run through the pre-commit and tested on the server.
=> MicroVQA Support

vlmeval/dataset/__init__.py, vlmeval/dataset/image_mcq.py
Motivation
Multimodal evaluation supporting Microbench (μ-Bench).
Modification
Add the relevant code for the datasets of Microbench (μ-Bench).
Checklist
Before PR:
[√] Pre-commit or other linting tools are used to fix the potential lint issues.
[√] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
[√] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
[√] The documentation has been modified accordingly, like docstring or example tutorials.
=> Add Microbench

vlmeval/dataset/__init__.py, vlmeval/dataset/image_mcq.py
Support OmniMedVQA dataset, has been tested and verified through pre-commit
=> Omnimed Support

vlmeval/dataset/__init__.py, vlmeval/dataset/image_mcq.py
**Motivation**
Multimodal evaluation support for the *MSEarthMCQ Benchmark* in the Earth science domain.
**Modification**
Added the necessary code to integrate the *MSEarthMCQ Benchmark* datasets with the evaluation framework.
**Note**
The currently submitted version of the dataset is **not in TSV format**. If any issues arise, we will upload a new version to Hugging Face accordingly.
=> [Benchmark]:Support MSEarthMCQ Benchmark

vlmeval/config.py, vlmeval/vlm/__init__.py, vlmeval/vlm/wethink_vl.py
Add support for WeThink-Qwen2.5VL-7B
=> [Model]  Add support for WeThink-Qwen2.5VL-7B

vlmeval/config.py, vlmeval/dataset/mlvu.py, vlmeval/dataset/mvbench.py, vlmeval/dataset/tempcompass.py
Changing position of visual tokens in MVBench significantly improves the performance of some models like Qwen2.5-VL
Qwen2.5-VL-7B 技术报告  69.6
Qwen2.5-VL-7B 复现64frames - 修正前  52.7
Qwen2.5-VL-7B 复现64frames - 修正后  67.7
=> change position of visual tokens in MVBench

vlmeval/dataset/charxiv.py
=> [minor] fix bug in charxiv

README.md, requirements.txt, vlmeval/dataset/__init__.py, vlmeval/dataset/gobench.py, vlmeval/dataset/image_vqa.py, vlmeval/dataset/utils/seephys.py
Add support for **SeePhys** benchmark, which is a ​full spectrum multimodal benchmark for evaluating physics reasoning across different knowledge levels.
Paper:[SeePhys: Does Seeing Help Thinking? -- Benchmarking Vision-Based Physics Reasoning
](https://arxiv.org/abs/2505.19099)
GitHub: [SeePhys](https://github.com/SeePhys/seephys-project)
=> [Benchmark] Support SeePhys benchmark

vlmeval/config.py, vlmeval/vlm/__init__.py, vlmeval/vlm/glm4_1v.py
This PR adds support for the GLM-4.1V-9B models from THUDM:
- **THUDM/GLM-4.1V-9B-Base**: The base vision-language model.
- **THUDM/GLM-4.1V-9B-Thinking**: The thinking-enhanced version for advanced reasoning-enhanced tasks.
- Supports inference with both Transformers and vLLM.
- Handles multi-image and interleaved inputs for flexible multimodal processing.
To use these models, ensure the following:
- Install the latest Transformers from GitHub: `pip install git+https://github.com/huggingface/transformers.git`
- vLLM version >= 0.9.2: `pip install -U vllm`
=> [Model] Add GLM-4.1V-9B

vlmeval/dataset/image_yorn.py, vlmeval/dataset/utils/yorn.py
Support [Visual Spatial Reasoning](https://arxiv.org/abs/2205.00363) (Zero-Shot).
Dataset: https://huggingface.co/datasets/cambridgeltl/vsr_zeroshot
=> [Benchmark] Support VSR  [TACL'23] 

vlmeval/vlm/sail_vl.py
你好！
我们是抖音内容理解团队，我们对评估的代码逻辑做进一步的更新，更新之前的部分数据集处理逻辑，非常抱歉，希望能基于最新的评测代码进行评测
=> 更新sailVL之前的部分数据集处理逻辑

vlmeval/config.py, vlmeval/vlm/__init__.py, vlmeval/vlm/logics.py
**Overview**
This PR adds support for Logics-Thinking-32B model .
**Evaluation Environment**
Our evaluation was conducted with the following packages and versions: `transformers==4.51.0`,`torch==2.5.1`,`pillow==10.4.0`,`opencv-python==4.12.0.88`,`deepspeed==0.16.0`.
**Changes in this PR**
- vlmeval/config.py
- vlmeval/vlm/logics.py
=> [Model] Add Logics-Thinking-32B

vlmeval/dataset/image_mcq.py
Initially, the options of TreeBench.tsv are stored in the "multi-choice options" key, which is not the official solution, i.e., store each option separately in "A", "B", "C", and "D" keys.
Therefore, this PR is to fix this.
=> Transfer TreeBench to official MCQ format
